image: bjodah/dockerfile-bjodah-scicomp:14.04b
git:
    path: github.com/bjodah/pyodeint
script:
  - if [[ "$DRONE_BRANCH" =~ ^v[0-9]+.[0-9]?* ]]; then export PYODEINT_RELEASE_VERSION=$DRONE_BRANCH; echo ${PYODEINT_RELEASE_VERSION} | tail -c +2 > __conda_version__.txt; fi
  - ./scripts/run_tests.sh
  - python setup.py sdist
  - ./scripts/generate_docs.sh
  - tar cjf doc.tar.bz2 doc/
  - scp doc.tar.bz2 dist/* pyodeint@hera.physchem.kth.se:~/
  - touch doc/_build/html/.nojekyll
  - git config --global user.name "drone"
  - git config --global user.email "drone@hera.physchem.kth.se"
  - if [[ "$DRONE_BRANCH" == "master" ]]; then ./scripts/github_upload.sh doc/_build/html bjodah pyodeint gh-pages; fi
