image: bjodah/dockerfile-bjodah-scicomp
git:
    path: github.com/bjodah/pyodeint
script:
  - python2 setup.py build_ext --inplace
  - python3 setup.py build_ext --inplace
  - PYTHONPATH=$(pwd) python2 -m pytest
  - PYTHONPATH=$(pwd) python3 -m pytest
