image: bjodah/dockerfile-bjodah-scicomp:14.04b
git:
    path: github.com/bjodah/pyodeint
env:
  - MY_SERVER=pyodeint@hera.physchem.kth.se
script:
  - if [[ "$DRONE_BRANCH" =~ ^v[0-9]+.[0-9]?* ]]; then export PYODEINT_RELEASE_VERSION=$DRONE_BRANCH; echo ${PYODEINT_RELEASE_VERSION} | tail -c +2 > __conda_version__.txt; fi
  - python3.4 setup.py build_ext -i
  - python2.7 setup.py build_ext -i
  - PYTHONPATH=$(pwd) ./scripts/run_tests.sh --cov pyodeint --cov-report html
  - python setup.py sdist
  - ./scripts/generate_docs.sh
  - ./scripts/coverage_badge.py htmlcov/ htmlcov/coverage.svg
  - ssh "${MY_SERVER}" "mkdir -p ~/public_html/$DRONE_BRANCH" && scp -r doc/ dist/* htmlcov/ ${MY_SERVER}:~/public_html/$DRONE_BRANCH
  - touch doc/_build/html/.nojekyll
  - git config --global user.name "drone"
  - git config --global user.email ${MY_SERVER}
  - if [[ "$DRONE_BRANCH" == "master" ]]; then ./scripts/github_upload.sh doc/_build/html bjodah pyodeint gh-pages; fi
