package:
  name: pyodeint
  version: 0.7.0.git

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - boost ==1.57.0
    - cython
  run:
    - numpy
    - python

test:
  imports:
    - pyodeint
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs pyodeint

about:
  home: https://github.com/bjodah/pyodeint
  license: Simplified BSD license
